---
title: Robin Péricé's Blog
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
encoding: UTF-8
exclude:
- "*.gem"
- "*.gemspec"
- Gemfile
- Gemfile.lock
- node_modules
- Rakefile
- starter-kit
- vendor
lang: en
permalink: "/blog/:year/:month/:day/:title/"
whitelist:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
markdown: kramdown
kramdown:
  auto_id_prefix: heading-
  smart_quotes:
  - apos
  - apos
  - quot
  - quot
  toc_levels: 1..3
sass:
  style: compressed
url: https://r0perice.github.io/blog/
baseurl: 
description: 
keywords: 
author:
  name: 
  job_title: 
  location: 
  email: 
  social_links:
  - name: github
    url: https://github.com/r0perice
  - name: linkedin
    url: https://www.linkedin.com/in/robinperice/
  - name: stackoverflow
    url: https://stackoverflow.com/users/6124935/robin-perice
  - name: twitter
    url: 
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/
  cc_license_image: "/assets/images/theme/cc-by-sa.png"
  footer_content: A gem-based responsive simple texture styled <a href="http://jekyllrb.com/">Jekyll</a>
    theme.
disqus:
  shortname: 
  public_key: 
google_tag_manager: 
addthis_public_id: 
paths:
  categories: "/categories/"
  tags: "/tags/"
  blog: 
